### ISSUE TITLE
Seeing both p1 and p01

### ISSUE THREAD

**Issue by RhysU** [ghollisjr/splitpdf#1]
Atop
```
$ calc -v
C-style arbitrary precision calculator w/custom functions (version 2.12.4.4)
```
I see duplicate files for single-digit pages.  For example, base_p1.pdf and base_p01.pdf.

**Comment by RhysU** [comment]
Thank you for the tool-- quite handy.

**Comment by ghollisjr** [comment]
Hey you're welcome, I tested splitpdf on a few of my own files and I don't see any duplicates for single-digit pages; do you have an example file that reproduces this problem?

**Comment by RhysU** [comment]
I'd be willing to bet it's how I generated the PDF.  Closing.
